# Generated by Django 4.2.5 on 2023-10-02 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recon', '0005_alter_bank_swift_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbankmapping',
            name='id',
        ),
        migrations.AlterField(
            model_name='userbankmapping',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
