# Generated by Django 4.2.5 on 2023-10-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0006_remove_userbankmapping_id_alter_userbankmapping_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
